# Generated by Django 4.1.1 on 2022-09-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_rename_message_contact_message_contact_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='prix',
            field=models.CharField(max_length=50),
        ),
    ]
