# Generated by Django 4.1.1 on 2022-09-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_alter_contact_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reseausocial',
            name='Icon',
        ),
        migrations.AddField(
            model_name='reseausocial',
            name='image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
