# Generated by Django 4.1.1 on 2022-09-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_remove_reseausocial_image_remove_service_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='')),
                ('libelle', models.CharField(max_length=200)),
            ],
        ),
    ]
